export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCESS = "ALL_PRODUCTS_SUCESS";
export const ALL_PRODUCTS_FAIL= "ALL_PRODUCTS_FAIL";

export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCTS_REQUEST";
export const ADMIN_PRODUCTS_SUCESS  = "ADMIN_PRODUCTS_SUCESS";
export const ADMIN_PRODUCTS_FAIL    = "ADMIN_PRODUCTS_FAIL";

export const ALL_PRODUCTS_DETAIL_REQUEST = "ALL_PRODUCTS_DETAIL_REQUEST";
export const ALL_PRODUCTS_DETAIL_SUCESS  = "ALL_PRODUCTS_DETAIL_SUCESS";
export const ALL_PRODUCTS_DETAIL_FAIL    = "ALL_PRODUCTS_DETAIL_FAIL";
export const ALL_PRODUCTS_DETAIL_RESET    = "ALL_PRODUCTS_DETAIL_RESET";

export const NEW_REVIEW_REQUEST_REQUEST = "NEW_REVIEW_REQUEST_REQUEST";
export const NEW_REVIEW_REQUEST_SUCESS  = "NEW_REVIEW_REQUEST_SUCESS";
export const NEW_REVIEW_REQUEST_FAIL    = "NEW_REVIEW_REQUEST_FAIL";
export const NEW_REVIEW_REQUEST_RESET    = "NEW_REVIEW_REQUEST_RESET";

export const NEW_PRODUCT_REQUEST         =  "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_REQUEST_SUCESS  = "NEW_PRODUCT_REQUEST_SUCESS";
export const NEW_PRODUCT_REQUEST_FAIL    = "NEW_PRODUCT_REQUEST_FAIL";
export const NEW_PRODUCT_RESET    = "NEW_PRODUCT_RESET";


export const DELETE_PRODUCT_REQUEST         = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST_SUCESS  = "DELETE_PRODUCT_REQUEST_SUCESS";
export const DELETE_PRODUCT_REQUEST_FAIL    = "DELETE_PRODUCT_REQUEST_FAIL";
export const DELETE_PRODUCT_RESET           = "DELETE_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";




export const CLEAR_ERRORS= "CLEAR_ERRORS";